<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d9a11c0b-19c2-4184-9be5-0c2c467cbc11</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VaultLab.Application\VaultLab.Application.csproj" />
    <ProjectReference Include="..\VaultLab.Infrastructure\VaultLab.Infrastructure.csproj" />
  </ItemGroup>

</Project>
